"""Exact contracts for the small canonical CP-SCALE handoff state block."""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.handoff_state import HandoffStateError, parse_handoff_state


BEGIN = "<!-- CP_SCALE_STATE_BEGIN -->"
END = "<!-- CP_SCALE_STATE_END -->"


def _block(*lines: str) -> str:
    return "\n".join((BEGIN, *lines, END))


def test_an_exact_canonical_value_passes():
    state = parse_handoff_state(_block("POOL = NOT_AVAILABLE"))

    assert state == {"POOL": "NOT_AVAILABLE"}


def test_a_prefix_only_expectation_does_not_match_an_expanded_value():
    text = _block(
        "DHCP_POOL_CONFIGURATION_READBACK = "
        "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS",
    )
    # This is the old false positive and the reason this parser exists.
    assert "DHCP_POOL_CONFIGURATION_READBACK = NOT_AVAILABLE" in text

    actual = parse_handoff_state(text)

    assert actual["DHCP_POOL_CONFIGURATION_READBACK"] != "NOT_AVAILABLE"


def test_a_suffix_expanded_value_does_not_match_the_shorter_expected_value():
    actual = parse_handoff_state(_block("STATUS = MEASURED_UNSUPPORTED_ON_PT"))

    assert actual["STATUS"] != "MEASURED_UNSUPPORTED"


def test_spacing_around_the_separator_is_irrelevant():
    actual = parse_handoff_state(_block("  STATUS   =   OPEN / NOT VERIFIED  "))

    assert actual == {"STATUS": "OPEN / NOT VERIFIED"}


def test_duplicate_canonical_key_is_rejected():
    with pytest.raises(HandoffStateError, match="duplicate key"):
        parse_handoff_state(_block("STATUS = OPEN", "STATUS = CLOSED"))


def test_duplicate_state_block_is_rejected():
    text = f"{_block('STATUS = OPEN')}\n{_block('STATUS = CLOSED')}"

    with pytest.raises(HandoffStateError, match="exactly one.*BEGIN"):
        parse_handoff_state(text)


def test_malformed_canonical_line_is_rejected():
    with pytest.raises(HandoffStateError, match="malformed canonical line"):
        parse_handoff_state(_block("STATUS OPEN"))


def test_historical_key_value_text_outside_the_block_is_ignored():
    text = "STATUS = HISTORICAL\n" + _block("STATUS = CURRENT")

    assert parse_handoff_state(text) == {"STATUS": "CURRENT"}


def test_multiline_canonical_value_is_rejected():
    text = _block("STATUS = FIRST LINE", "    SECOND LINE")

    with pytest.raises(HandoffStateError, match="malformed canonical line"):
        parse_handoff_state(text)


@pytest.mark.parametrize("text", ["STATUS = OPEN", f"{BEGIN}\nSTATUS = OPEN"])
def test_a_missing_required_marker_is_rejected(text: str):
    with pytest.raises(HandoffStateError, match="exactly one"):
        parse_handoff_state(text)


def test_current_cp_scale_voice_state_uses_exact_values():
    handoff = Path("handoff.md").read_text(encoding="utf-8")
    expected = {
        "DHCP_DORA_QUERY_STATUS": "MEASURED_UNSUPPORTED",
        "DORA_EXISTING_SURFACE_USABLE": "NO",
        "DORA_QUERY_READBACK": "UNOBSERVABLE",
        "FIRST_DHCP_RUNTIME_BOUNDARY": "NOT_ESTABLISHED",
        "FIRST_COMMON_VOICE_OBSERVABILITY_BOUNDARY": (
            "ENDPOINT_ADDRESS_CONTRADICTED"
        ),
        "DHCP_POOL_EXISTENCE_READBACK": "VERIFIED",
        "DHCP_POOL_RANGE_READBACK": "VERIFIED",
        "DHCP_POOL_AVAILABLE_SPACE_READBACK": "VERIFIED",
        "DHCP_POOL_CONFIGURATION_READBACK": (
            "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS"
        ),
        "DHCP_POOL_DEFAULT_ROUTER_READBACK": (
            "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS"
        ),
        "DHCP_POOL_EXCLUSIONS_READBACK": (
            "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS"
        ),
        "POOL_EXISTENCE_CAUSE": "WEAKENED",
        "POOL_EXHAUSTION_CAUSE": "REFUTED_FOR_THIS_DISPOSABLE",
        "OPTION150_READBACK": "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS",
        "PORTFAST_CAUSAL_BRANCH": "CLOSED_FOR_NOW",
        "PORTFAST_AS_VOICE_ROOT_CAUSE": (
            "STRONGLY_WEAKENED_FOR_GOVERNED_DISPATCH"
        ),
        "SERVER_RECEIVES_DISCOVER": "UNOBSERVABLE",
        "DHCP_TRANSACTION_PROGRESS": "UNOBSERVABLE",
        "VOICE_VLAN_REALTIME_DATA_PLANE_FORWARDING": "NOT_ESTABLISHED",
        "ACCESS_VLAN_SHAPE_CONTROLS_STP_MEMBERSHIP": "ESTABLISHED",
        "ACCESS_VLAN_SHAPE_CONTROLS_DHCP": "NOT_YET_ESTABLISHED",
        "VOICE_ENDPOINT_OUTCOME_RUN9": "SAME_FAILURE",
        "CAUSAL_EXPERIMENT_RESULT_RUN9": "PARTIAL_OR_DIVERGENT",
        "INTERVENTION_FWD_OBSERVED_RUN9": "NO",
        "INTERVENTION_NEVER_FWD_DURING_RUN9": "NOT_ESTABLISHED",
        "FRESH_DHCP_TRIGGER": (
            "NOT_ESTABLISHED_RUN11_PRE_FLAGS_ALREADY_YES"
        ),
        "FRESH_7960_DHCP_TRANSACTION": "NOT_INDEPENDENTLY_ESTABLISHED",
        "CURRENT_TYPED_DHCP_FRESH_TRANSACTION": "NOT_ESTABLISHED",
        "PHONE_SVI_DHCP_API": (
            "MEASURED_PRESENT_AND_CISCO_BOOL_SIGNATURE_CONFIRMED"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_EXPERIMENT": (
            "RUN13_EXECUTED_NO_ADDRESS"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_NETWORK_SHAPE": (
            "P1_ACCESS930_VOICE930 | P2_ACCESS930_VOICE930"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_FWD_GATES": (
            "P1_AUTHORITATIVE_FWD + P2_AUTHORITATIVE_FWD_REQUIRED"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_CONTROL_INVARIANT": (
            "P1_PRE_YES + P1_POST_YES + NEVER_MUTATED"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_LEDGER_ROLE": (
            "PHONE_SVI_DHCP_RETRIGGER_CAUSAL_INTERVENTION"
        ),
        "RUN13_EXECUTED": "YES",
        "RUN13_SOURCE_HEAD": (
            "718075318b18126dd672ec7dfda4fd1faf101f70"
        ),
        "RUN13_RESULT": "NO_ADDRESS_AFTER_PHONE_SVI_DHCP_RETRIGGER",
        "RUN13_CONTROL_FWD_GATE": "FORWARDING_AUTHORITATIVE",
        "RUN13_INTERVENTION_FWD_GATE": "FORWARDING_AUTHORITATIVE",
        "RUN13_BOTH_AUTHORITATIVE_FWD": "YES",
        "RUN13_CONTROL_PRE_ENDPOINT": (
            "SVI_YES | CHANNEL_YES | DHCP_YES | IPV4_EMPTY | ADDRESSED_NO"
        ),
        "RUN13_INTERVENTION_PRE_ENDPOINT": (
            "SVI_YES | CHANNEL_YES | DHCP_YES | IPV4_EMPTY | ADDRESSED_NO"
        ),
        "RUN13_PRE_RETRIGGER_ADDRESS_BASELINE_VALID": "YES",
        "RUN13_CONTROL_MUTATED": "NO",
        "RUN13_CONTROL_DHCP_POST": "YES",
        "RUN13_INTERVENTION_TRANSITION": (
            "YES -> NO -> YES | ACCEPTED_YES_YES | READBACK_NO_YES"
        ),
        "RUN13_INTERVENTION_TRANSITION_VALID": "YES",
        "RUN13_ACQUISITION_WINDOW_AUTHORIZED": "YES",
        "RUN13_CONTROL_FINAL_IPV4": "EMPTY",
        "RUN13_INTERVENTION_FINAL_IPV4": "EMPTY",
        "RUN13_CONTROL_ADDRESSED": "NO",
        "RUN13_INTERVENTION_ADDRESSED": "NO",
        "RUN13_VOICE_BINDING_COUNT": "0",
        "RUN13_MATCHING_INTERVENTION_BINDING": "NO",
        "RUN13_CONTROL_SCCP": "NOT_REGISTERED",
        "RUN13_INTERVENTION_SCCP": "NOT_REGISTERED",
        "RUN13_SHA256": (
            "8054b128b2a74cdc380e10b5eff03a80a08f1b75474ac10bfbbb9c5399df8c8a"
        ),
        "RUN13_WORKSPACE_RESTORED": "YES",
        "RUN13_REALTIME_RESTORED": "YES",
        "RAW_VOICE_AB_RUNS_PINNED": "14",
        "NEW_MUTATION_SURFACE": "TYPED_EXACT_PHONE_SVI_ONLY",
        "RAW_ESCAPE_HATCH_ADDED": "NO",
        "PHONE_DHCP_LIFECYCLE_DIAGNOSTIC": "MEASURED",
        "PHONE_DHCP_LIFECYCLE_LIVE_EXECUTED": "YES",
        "PHONE_DHCP_LIFECYCLE_CHANNELS": "SVI_DHCP | DEVICE_DHCP",
        "PHONE_DHCP_LIFECYCLE_DERIVATIONS": "PER_PHONE",
        "PHONE_DHCP_LIFECYCLE_LEDGER_ROLE": (
            "PHONE_DHCP_LIFECYCLE_QUALIFICATION"
        ),
        "FIRST_OBSERVED_SVI_DHCP_ENABLED_MILESTONE": (
            "IMMEDIATELY_BEFORE_STP_FWD_GATE"
        ),
        "FIRST_OBSERVED_DEVICE_DHCP_ENABLED_MILESTONE": "NOT_ESTABLISHED",
        "SVI_DHCP_ENABLED_BEFORE_FWD": "YES",
        "DEVICE_DHCP_ENABLED_BEFORE_FWD": "UNOBSERVABLE",
        "RUN12_EXECUTED": "YES",
        "RUN12_RESULT": "OBSERVATIONAL_LIFECYCLE_QUALIFIED",
        "RUN12_FWD_GATE": "FORWARDING",
        "RUN12_STP_GATE_OBSERVED_STATES": (
            "LIS -> LRN -> UNOBSERVABLE -> LRN -> UNOBSERVABLE -> FORWARDING"
        ),
        "RUN12_STP_AUTHORITY_TRANSITIONS": (
            "LIS(AUTHORITATIVE) -> LRN(AUTHORITATIVE) -> "
            "UNOBSERVABLE(COMPLETENESS) -> LRN(AUTHORITATIVE) -> "
            "UNOBSERVABLE(COMPLETENESS) -> FORWARDING(AUTHORITATIVE)"
        ),
        "RUN12_STP_FAILURE_DIMENSIONS": "COMPLETENESS",
        "RUN12_STP_GATE_DURATION_MS": "31171",
        "RUN12_STP_GATE_SAMPLES": "15",
        "RUN12_AUTHORITATIVE_FWD_OBSERVED": "YES",
        "RUN12_CONTROL_FIRST_SVI_DHCP_ENABLED": (
            "IMMEDIATELY_BEFORE_STP_FWD_GATE"
        ),
        "RUN12_INTERVENTION_FIRST_SVI_DHCP_ENABLED": (
            "IMMEDIATELY_BEFORE_STP_FWD_GATE"
        ),
        "RUN12_CONTROL_FIRST_DEVICE_DHCP_ENABLED": "NOT_ESTABLISHED",
        "RUN12_INTERVENTION_FIRST_DEVICE_DHCP_ENABLED": "NOT_ESTABLISHED",
        "RUN12_CONTROL_SVI_DHCP_BEFORE_FWD": "YES",
        "RUN12_INTERVENTION_SVI_DHCP_BEFORE_FWD": "YES",
        "RUN12_CONTROL_DEVICE_DHCP_BEFORE_FWD": "UNOBSERVABLE",
        "RUN12_INTERVENTION_DEVICE_DHCP_BEFORE_FWD": "UNOBSERVABLE",
        "RUN12_CONTROL_IPV4_OBSERVED": "NO_VALUE_OBSERVED",
        "RUN12_INTERVENTION_IPV4_OBSERVED": "NO_VALUE_OBSERVED",
        "RUN12_OBSERVABLE_DHCP_NO_TO_YES_TRANSITION": "NOT_OBSERVED",
        "RUN10_EXECUTED": "YES",
        "RUN10_RESULT": "STP_PRECONDITION_NOT_ESTABLISHED",
        "RUN10_FWD_GATE": "UNOBSERVABLE",
        "RUN10_STP_GATE_OBSERVED_STATES": "LIS -> LRN -> UNOBSERVABLE",
        "RUN10_STP_GATE_DURATION_MS": "21844",
        "RUN10_STP_GATE_SAMPLES": "11",
        "RUN10_STP_GATE_IDENTITY": "NOT_ESTABLISHED",
        "RUN10_TERMINAL_STP_FAILURE_DIMENSION": "NOT_RETAINED",
        "STP_GATE_DIAGNOSTIC_RETENTION": "READY",
        "STP_GATE_GAP_TOLERANCE": "READY",
        "STP_GATE_SUCCESS_CONTRACT": (
            "EXECUTED + FRESH + COMPLETE + CONFIRMED_UNIQUE + FWD"
        ),
        "STP_GATE_FAILURE_DIMENSIONS": (
            "EXECUTION | FRESHNESS | COMPLETENESS | IDENTITY | PARSING | "
            "QUERY_SESSION"
        ),
        "STP_GATE_QUERY_COUNT_PER_SAMPLE": "ONE",
        "SECOND_STP_QUERY_ADDED": "NO",
        "RUN10_DHCP_FLAG_TRANSITION_CONTRACT": (
            "PRE_NO + ARM_ACCEPTED + POST_YES_REQUIRED"
        ),
        "RUN10_DHCP_FLAG_TRANSITION": "UNOBSERVABLE",
        "RUN10_ACQUISITION_STARTED": "NO",
        "RUN10_ACQUISITION_BOUNDARY": (
            "ACQUISITION_NOT_STARTED_STP_PRECONDITION_UNMET"
        ),
        "RUN10_TRUNK_VOICE_FORWARDING": "CONTRADICTED",
        "RUN10_TRUNK_ALLOWED_VLANS": "NOT_RETAINED",
        "RUN10_TRUNK_ACTIVE_VLANS": "NOT_RETAINED",
        "RUN10_TRUNK_FORWARDING_VLANS": "NOT_RETAINED",
        "RUN10_TRUNK_VLAN930_ALLOWED": "YES",
        "RUN10_TRUNK_VLAN930_ACTIVE": "YES",
        "RUN10_TRUNK_VLAN930_FORWARDING": "NO",
        "RUN11_EXECUTED": "YES",
        "RUN11_RESULT": "FRESH_DHCP_TRIGGER_UNPROVEN",
        "RUN11_FWD_GATE": "FORWARDING",
        "RUN11_STP_GATE_OBSERVED_STATES": (
            "LIS -> LRN -> UNOBSERVABLE -> LRN -> UNOBSERVABLE -> FORWARDING"
        ),
        "RUN11_STP_AUTHORITY_TRANSITIONS": (
            "LIS(AUTHORITATIVE) -> LRN(AUTHORITATIVE) -> "
            "UNOBSERVABLE(COMPLETENESS) -> LRN(AUTHORITATIVE) -> "
            "UNOBSERVABLE(COMPLETENESS) -> FORWARDING(AUTHORITATIVE)"
        ),
        "RUN11_STP_FAILURE_DIMENSIONS": "COMPLETENESS",
        "RUN11_STP_GATE_DURATION_MS": "30327",
        "RUN11_STP_GATE_SAMPLES": "15",
        "RUN11_AUTHORITATIVE_FWD_OBSERVED": "YES",
        "RUN11_TRUNK_ALLOWED_VLANS": "(930, 931)",
        "RUN11_TRUNK_ACTIVE_VLANS": "(930, 931)",
        "RUN11_TRUNK_FORWARDING_VLANS": "(930, 931)",
        "RUN11_TRUNK_READ_AUTHORITY": "AUTHORITATIVE",
        "RUN11_CONTROL_DHCP_PRE": "YES",
        "RUN11_INTERVENTION_DHCP_PRE": "YES",
        "RUN11_CONTROL_ARM_ACCEPTED": "UNOBSERVABLE",
        "RUN11_INTERVENTION_ARM_ACCEPTED": "UNOBSERVABLE",
        "RUN11_CONTROL_DHCP_POST": "UNOBSERVABLE",
        "RUN11_INTERVENTION_DHCP_POST": "UNOBSERVABLE",
        "RUN11_DHCP_FLAG_TRANSITION_VALID": "UNOBSERVABLE",
        "RUN11_ACQUISITION_STARTED": "NO",
        "RUN11_ACQUISITION_BOUNDARY": (
            "ACQUISITION_NOT_STARTED_FRESH_DHCP_TRIGGER_UNPROVEN"
        ),
        "TRUNK_FORWARDING_SEMANTIC_AUDIT": (
            "IOS_STP_FORWARDING_AND_NOT_PRUNED_SET_ON_SHARED_TRUNK"
        ),
        "TRUNK_READ_AUTHORITY_RETENTION": "READY",
        "STP_VS_TRUNK_RELATION": "NOT_ESTABLISHED",
        "RUN14_EXECUTED": "YES",
        "RUN14_SOURCE_HEAD": (
            "3592b73e28024ffe4f94decc829ffd05290bc57a"
        ),
        "RUN14_SOURCE_HEAD_STATUS": (
            "REVERTED_BY_4a5adc69c8f54d1f9807e0988b575cf7d7f1412b"
        ),
        "RUN14_RESULT": "SAME_FAILURE_ACTIVATION_CALL_NOT_ACCEPTED",
        "RUN14_EXPERIMENT": "UNIFORM_BASELINE",
        "RUN14_ARM_INTERFACE": "Vlan1",
        "RUN14_ARM_ACCEPTED": "NO_FOR_BOTH_PHONES",
        "RUN14_ARM_ERRORS": (
            "endpoint_dhcp_not_accepted:P1 | endpoint_dhcp_not_accepted:P2"
        ),
        "RUN14_ARM_REFUSAL_REASON_INSTRUMENTED": "NO",
        "RUN14_NETWORK_SHAPE": (
            "P1_ACCESS931_VOICE930 | P2_ACCESS931_VOICE930"
        ),
        "RUN14_PRE_ARM_SVI_DHCP": "YES_FOR_BOTH_PHONES",
        "RUN14_PHONE_STP_ROWS": "ABSENT_BEFORE_AND_AFTER",
        "RUN14_FINAL_IPV4": "EMPTY_FOR_BOTH_PHONES",
        "RUN14_VOICE_BINDING_COUNT": "0",
        "RUN14_SCCP": "NOT_REGISTERED_FOR_BOTH_PHONES",
        "RUN14_FIRST_BOUNDARY": "ENDPOINT_ADDRESS_CONTRADICTED",
        "RUN14_WORKSPACE_RESTORED": "YES",
        "RUN14_REALTIME_RESTORED": "YES",
        "RUN14_CLEANUP_ERRORS": "NONE",
        "RUN14_CONTRACT_VALID": (
            "YES_AS_A_BASELINE_ONLY_NOT_AS_AN_INTERVENTION"
        ),
        "RUN14_SHA256": (
            "f44347d0ffb46f380259443ed3455791346d631cd0ec7c8e31ee7365c409089a"
        ),
        "E5_PHONE_DHCP_ACTIVATION_HYPOTHESIS": "REFUTED",
        "E5_PHONE_DHCP_ACTIVATION_REFUTATION_BASIS": (
            "VLAN1_DOWN_ONCE_VOICE_VLAN_SIGNALLED + NO_OFF_STATE_TO_FLIP + "
            "RUN13_VALID_TRANSITION_NO_ADDRESS"
        ),
        "HISTORICAL_E5_PHONE_ADDRESSING_WAS_A_NO_OP": (
            "ESTABLISHED_FROM_6ea254d_MEASUREMENT"
        ),
        "HISTORICAL_POSITIVE_SLICE_WAS_MANUAL": (
            "ESTABLISHED_FROM_2e7f0f5_DOC"
        ),
        "FIRST_SURVIVING_CAUSAL_DIVERGENCE": (
            "SINGLE_EARLY_PHONE_DISCOVER_VERSUS_ACCESS_PORT_STP_CONVERGENCE"
        ),
        "FRESH_DHCP_TRANSACTION_TRIGGER": (
            "STILL_NOT_AVAILABLE_IN_TYPED_RUNTIME"
        ),
        "RUN15_MODE_PREPARED": "EDGE_BEFORE_VOICE_VLAN",
        "RUN15_LEDGER_ROLE": (
            "EDGE_BEFORE_VOICE_VLAN_CAUSAL_INTERVENTION"
        ),
        "RUN15_VARIABLE": (
            "TYPED_EDGE_POLICY_ON_INTERVENTION_PORT_BEFORE_VOICE_VLAN"
        ),
        "RUN15_NETWORK_SHAPE": (
            "P1_ACCESS931_VOICE930 | P2_ACCESS931_VOICE930"
        ),
        "RUN15_DHCP_MUTATIONS": "NONE",
        "RUN15_FOUNDATION_GATE": (
            "SHARED_FOUNDATION_VERIFIED_BEFORE_VOICE_VLAN_REQUIRED"
        ),
        "RUN15_CLOCK_BOUNDARY": (
            "ONE_SHARED_VOICE_VLAN_BATCH_FOR_BOTH_PORTS"
        ),
        "RUN15_GATE_QUERY_COUNT_PER_SAMPLE": "ONE_SHARED_BY_BOTH_PORTS",
        "RUN15_MILESTONES": (
            "IMMEDIATELY_AFTER_VOICE_VLAN | FIRST_AUTHORITATIVE_STP_SAMPLE | "
            "AUTHORITATIVE_FWD | END_OF_ACQUISITION_WINDOW"
        ),
        "RUN15_EXECUTED": "NO",
        "VOICE_ROOT_CAUSE": "NOT_CONFIRMED",
        "VOICE_ROOT_CAUSE_LEADING_CANDIDATE": "EARLY_DISCOVER_LOST_NO_RETRY",
        "PRODUCTION_FIX_JUSTIFIED": "NOT_YET",
        "NEXT_ACTIVE_STEP": (
            "EXECUTE_RUN15_EDGE_BEFORE_VOICE_VLAN_LIVE_ONCE"
        ),
        "CP_SCALE_STATUS": "OPEN / NOT VERIFIED",
    }

    actual = parse_handoff_state(handoff)

    assert actual == expected
