"""Exact contracts for the small canonical CP-SCALE handoff state block."""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.handoff_state import HandoffStateError, parse_handoff_state


BEGIN = "<!-- CP_SCALE_STATE_BEGIN -->"
END = "<!-- CP_SCALE_STATE_END -->"


def _block(*lines: str) -> str:
    return "\n".join((BEGIN, *lines, END))


def test_an_exact_canonical_value_passes():
    state = parse_handoff_state(_block("POOL = NOT_AVAILABLE"))

    assert state == {"POOL": "NOT_AVAILABLE"}


def test_a_prefix_only_expectation_does_not_match_an_expanded_value():
    text = _block(
        "DHCP_POOL_CONFIGURATION_READBACK = "
        "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS",
    )
    # This is the old false positive and the reason this parser exists.
    assert "DHCP_POOL_CONFIGURATION_READBACK = NOT_AVAILABLE" in text

    actual = parse_handoff_state(text)

    assert actual["DHCP_POOL_CONFIGURATION_READBACK"] != "NOT_AVAILABLE"


def test_a_suffix_expanded_value_does_not_match_the_shorter_expected_value():
    actual = parse_handoff_state(_block("STATUS = MEASURED_UNSUPPORTED_ON_PT"))

    assert actual["STATUS"] != "MEASURED_UNSUPPORTED"


def test_spacing_around_the_separator_is_irrelevant():
    actual = parse_handoff_state(_block("  STATUS   =   OPEN / NOT VERIFIED  "))

    assert actual == {"STATUS": "OPEN / NOT VERIFIED"}


def test_duplicate_canonical_key_is_rejected():
    with pytest.raises(HandoffStateError, match="duplicate key"):
        parse_handoff_state(_block("STATUS = OPEN", "STATUS = CLOSED"))


def test_duplicate_state_block_is_rejected():
    text = f"{_block('STATUS = OPEN')}\n{_block('STATUS = CLOSED')}"

    with pytest.raises(HandoffStateError, match="exactly one.*BEGIN"):
        parse_handoff_state(text)


def test_malformed_canonical_line_is_rejected():
    with pytest.raises(HandoffStateError, match="malformed canonical line"):
        parse_handoff_state(_block("STATUS OPEN"))


def test_historical_key_value_text_outside_the_block_is_ignored():
    text = "STATUS = HISTORICAL\n" + _block("STATUS = CURRENT")

    assert parse_handoff_state(text) == {"STATUS": "CURRENT"}


def test_multiline_canonical_value_is_rejected():
    text = _block("STATUS = FIRST LINE", "    SECOND LINE")

    with pytest.raises(HandoffStateError, match="malformed canonical line"):
        parse_handoff_state(text)


@pytest.mark.parametrize("text", ["STATUS = OPEN", f"{BEGIN}\nSTATUS = OPEN"])
def test_a_missing_required_marker_is_rejected(text: str):
    with pytest.raises(HandoffStateError, match="exactly one"):
        parse_handoff_state(text)


def test_current_cp_scale_voice_state_uses_exact_values():
    handoff = Path("handoff.md").read_text(encoding="utf-8")
    expected = {
        "DHCP_DORA_QUERY_STATUS": "MEASURED_UNSUPPORTED",
        "DORA_EXISTING_SURFACE_USABLE": "NO",
        "DORA_QUERY_READBACK": "UNOBSERVABLE",
        "FIRST_DHCP_RUNTIME_BOUNDARY": "NOT_ESTABLISHED",
        "FIRST_COMMON_VOICE_OBSERVABILITY_BOUNDARY": (
            "ENDPOINT_ADDRESS_CONTRADICTED"
        ),
        "DHCP_POOL_EXISTENCE_READBACK": "VERIFIED",
        "DHCP_POOL_RANGE_READBACK": "VERIFIED",
        "DHCP_POOL_AVAILABLE_SPACE_READBACK": "VERIFIED",
        "DHCP_POOL_CONFIGURATION_READBACK": (
            "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS"
        ),
        "DHCP_POOL_DEFAULT_ROUTER_READBACK": (
            "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS"
        ),
        "DHCP_POOL_EXCLUSIONS_READBACK": (
            "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS"
        ),
        "POOL_EXISTENCE_CAUSE": "WEAKENED",
        "POOL_EXHAUSTION_CAUSE": "REFUTED_FOR_THIS_DISPOSABLE",
        "OPTION150_READBACK": "NOT_AVAILABLE_WITH_CURRENT_GOVERNED_READBACKS",
        "PORTFAST_CAUSAL_BRANCH": "CLOSED_FOR_NOW",
        "PORTFAST_AS_VOICE_ROOT_CAUSE": (
            "STRONGLY_WEAKENED_FOR_GOVERNED_DISPATCH"
        ),
        "SERVER_RECEIVES_DISCOVER": "UNOBSERVABLE",
        "DHCP_TRANSACTION_PROGRESS": "UNOBSERVABLE",
        "VOICE_VLAN_REALTIME_DATA_PLANE_FORWARDING": "NOT_ESTABLISHED",
        "ACCESS_VLAN_SHAPE_CONTROLS_STP_MEMBERSHIP": "ESTABLISHED",
        "ACCESS_VLAN_SHAPE_CONTROLS_DHCP": "NOT_YET_ESTABLISHED",
        "VOICE_ENDPOINT_OUTCOME_RUN9": "SAME_FAILURE",
        "CAUSAL_EXPERIMENT_RESULT_RUN9": "PARTIAL_OR_DIVERGENT",
        "INTERVENTION_FWD_OBSERVED_RUN9": "NO",
        "INTERVENTION_NEVER_FWD_DURING_RUN9": "NOT_ESTABLISHED",
        "FRESH_DHCP_TRIGGER": (
            "NOT_ESTABLISHED_RUN11_PRE_FLAGS_ALREADY_YES"
        ),
        "FRESH_7960_DHCP_TRANSACTION": "NOT_INDEPENDENTLY_ESTABLISHED",
        "CURRENT_TYPED_DHCP_FRESH_TRANSACTION": "NOT_ESTABLISHED",
        "PHONE_SVI_DHCP_API": (
            "MEASURED_PRESENT_AND_CISCO_BOOL_SIGNATURE_CONFIRMED"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_EXPERIMENT": (
            "RUN13_EXECUTED_NO_ADDRESS"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_NETWORK_SHAPE": (
            "P1_ACCESS930_VOICE930 | P2_ACCESS930_VOICE930"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_FWD_GATES": (
            "P1_AUTHORITATIVE_FWD + P2_AUTHORITATIVE_FWD_REQUIRED"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_CONTROL_INVARIANT": (
            "P1_PRE_YES + P1_POST_YES + NEVER_MUTATED"
        ),
        "PHONE_SVI_DHCP_RETRIGGER_LEDGER_ROLE": (
            "PHONE_SVI_DHCP_RETRIGGER_CAUSAL_INTERVENTION"
        ),
        "RUN13_EXECUTED": "YES",
        "RUN13_SOURCE_HEAD": (
            "718075318b18126dd672ec7dfda4fd1faf101f70"
        ),
        "RUN13_RESULT": "NO_ADDRESS_AFTER_PHONE_SVI_DHCP_RETRIGGER",
        "RUN13_CONTROL_FWD_GATE": "FORWARDING_AUTHORITATIVE",
        "RUN13_INTERVENTION_FWD_GATE": "FORWARDING_AUTHORITATIVE",
        "RUN13_BOTH_AUTHORITATIVE_FWD": "YES",
        "RUN13_CONTROL_PRE_ENDPOINT": (
            "SVI_YES | CHANNEL_YES | DHCP_YES | IPV4_EMPTY | ADDRESSED_NO"
        ),
        "RUN13_INTERVENTION_PRE_ENDPOINT": (
            "SVI_YES | CHANNEL_YES | DHCP_YES | IPV4_EMPTY | ADDRESSED_NO"
        ),
        "RUN13_PRE_RETRIGGER_ADDRESS_BASELINE_VALID": "YES",
        "RUN13_CONTROL_MUTATED": "NO",
        "RUN13_CONTROL_DHCP_POST": "YES",
        "RUN13_INTERVENTION_TRANSITION": (
            "YES -> NO -> YES | ACCEPTED_YES_YES | READBACK_NO_YES"
        ),
        "RUN13_INTERVENTION_TRANSITION_VALID": "YES",
        "RUN13_ACQUISITION_WINDOW_AUTHORIZED": "YES",
        "RUN13_CONTROL_FINAL_IPV4": "EMPTY",
        "RUN13_INTERVENTION_FINAL_IPV4": "EMPTY",
        "RUN13_CONTROL_ADDRESSED": "NO",
        "RUN13_INTERVENTION_ADDRESSED": "NO",
        "RUN13_VOICE_BINDING_COUNT": "0",
        "RUN13_MATCHING_INTERVENTION_BINDING": "NO",
        "RUN13_CONTROL_SCCP": "NOT_REGISTERED",
        "RUN13_INTERVENTION_SCCP": "NOT_REGISTERED",
        "RUN13_SHA256": (
            "8054b128b2a74cdc380e10b5eff03a80a08f1b75474ac10bfbbb9c5399df8c8a"
        ),
        "RUN13_WORKSPACE_RESTORED": "YES",
        "RUN13_REALTIME_RESTORED": "YES",
        "RAW_VOICE_AB_RUNS_PINNED": "21",
        "NEW_MUTATION_SURFACE": "TYPED_EXACT_PHONE_SVI_ONLY",
        "RAW_ESCAPE_HATCH_ADDED": "NO",
        "PHONE_DHCP_LIFECYCLE_DIAGNOSTIC": "MEASURED",
        "PHONE_DHCP_LIFECYCLE_LIVE_EXECUTED": "YES",
        "PHONE_DHCP_LIFECYCLE_CHANNELS": "SVI_DHCP | DEVICE_DHCP",
        "PHONE_DHCP_LIFECYCLE_DERIVATIONS": "PER_PHONE",
        "PHONE_DHCP_LIFECYCLE_LEDGER_ROLE": (
            "PHONE_DHCP_LIFECYCLE_QUALIFICATION"
        ),
        "FIRST_OBSERVED_SVI_DHCP_ENABLED_MILESTONE": (
            "IMMEDIATELY_BEFORE_STP_FWD_GATE"
        ),
        "FIRST_OBSERVED_DEVICE_DHCP_ENABLED_MILESTONE": "NOT_ESTABLISHED",
        "SVI_DHCP_ENABLED_BEFORE_FWD": "YES",
        "DEVICE_DHCP_ENABLED_BEFORE_FWD": "UNOBSERVABLE",
        "RUN12_EXECUTED": "YES",
        "RUN12_RESULT": "OBSERVATIONAL_LIFECYCLE_QUALIFIED",
        "RUN12_FWD_GATE": "FORWARDING",
        "RUN12_STP_GATE_OBSERVED_STATES": (
            "LIS -> LRN -> UNOBSERVABLE -> LRN -> UNOBSERVABLE -> FORWARDING"
        ),
        "RUN12_STP_AUTHORITY_TRANSITIONS": (
            "LIS(AUTHORITATIVE) -> LRN(AUTHORITATIVE) -> "
            "UNOBSERVABLE(COMPLETENESS) -> LRN(AUTHORITATIVE) -> "
            "UNOBSERVABLE(COMPLETENESS) -> FORWARDING(AUTHORITATIVE)"
        ),
        "RUN12_STP_FAILURE_DIMENSIONS": "COMPLETENESS",
        "RUN12_STP_GATE_DURATION_MS": "31171",
        "RUN12_STP_GATE_SAMPLES": "15",
        "RUN12_AUTHORITATIVE_FWD_OBSERVED": "YES",
        "RUN12_CONTROL_FIRST_SVI_DHCP_ENABLED": (
            "IMMEDIATELY_BEFORE_STP_FWD_GATE"
        ),
        "RUN12_INTERVENTION_FIRST_SVI_DHCP_ENABLED": (
            "IMMEDIATELY_BEFORE_STP_FWD_GATE"
        ),
        "RUN12_CONTROL_FIRST_DEVICE_DHCP_ENABLED": "NOT_ESTABLISHED",
        "RUN12_INTERVENTION_FIRST_DEVICE_DHCP_ENABLED": "NOT_ESTABLISHED",
        "RUN12_CONTROL_SVI_DHCP_BEFORE_FWD": "YES",
        "RUN12_INTERVENTION_SVI_DHCP_BEFORE_FWD": "YES",
        "RUN12_CONTROL_DEVICE_DHCP_BEFORE_FWD": "UNOBSERVABLE",
        "RUN12_INTERVENTION_DEVICE_DHCP_BEFORE_FWD": "UNOBSERVABLE",
        "RUN12_CONTROL_IPV4_OBSERVED": "NO_VALUE_OBSERVED",
        "RUN12_INTERVENTION_IPV4_OBSERVED": "NO_VALUE_OBSERVED",
        "RUN12_OBSERVABLE_DHCP_NO_TO_YES_TRANSITION": "NOT_OBSERVED",
        "RUN10_EXECUTED": "YES",
        "RUN10_RESULT": "STP_PRECONDITION_NOT_ESTABLISHED",
        "RUN10_FWD_GATE": "UNOBSERVABLE",
        "RUN10_STP_GATE_OBSERVED_STATES": "LIS -> LRN -> UNOBSERVABLE",
        "RUN10_STP_GATE_DURATION_MS": "21844",
        "RUN10_STP_GATE_SAMPLES": "11",
        "RUN10_STP_GATE_IDENTITY": "NOT_ESTABLISHED",
        "RUN10_TERMINAL_STP_FAILURE_DIMENSION": "NOT_RETAINED",
        "STP_GATE_DIAGNOSTIC_RETENTION": "READY",
        "STP_GATE_GAP_TOLERANCE": "READY",
        "STP_GATE_SUCCESS_CONTRACT": (
            "EXECUTED + FRESH + COMPLETE + CONFIRMED_UNIQUE + FWD"
        ),
        "STP_GATE_FAILURE_DIMENSIONS": (
            "EXECUTION | FRESHNESS | COMPLETENESS | IDENTITY | PARSING | "
            "QUERY_SESSION"
        ),
        "STP_GATE_QUERY_COUNT_PER_SAMPLE": "ONE",
        "SECOND_STP_QUERY_ADDED": "NO",
        "RUN10_DHCP_FLAG_TRANSITION_CONTRACT": (
            "PRE_NO + ARM_ACCEPTED + POST_YES_REQUIRED"
        ),
        "RUN10_DHCP_FLAG_TRANSITION": "UNOBSERVABLE",
        "RUN10_ACQUISITION_STARTED": "NO",
        "RUN10_ACQUISITION_BOUNDARY": (
            "ACQUISITION_NOT_STARTED_STP_PRECONDITION_UNMET"
        ),
        "RUN10_TRUNK_VOICE_FORWARDING": "CONTRADICTED",
        "RUN10_TRUNK_ALLOWED_VLANS": "NOT_RETAINED",
        "RUN10_TRUNK_ACTIVE_VLANS": "NOT_RETAINED",
        "RUN10_TRUNK_FORWARDING_VLANS": "NOT_RETAINED",
        "RUN10_TRUNK_VLAN930_ALLOWED": "YES",
        "RUN10_TRUNK_VLAN930_ACTIVE": "YES",
        "RUN10_TRUNK_VLAN930_FORWARDING": "NO",
        "RUN11_EXECUTED": "YES",
        "RUN11_RESULT": "FRESH_DHCP_TRIGGER_UNPROVEN",
        "RUN11_FWD_GATE": "FORWARDING",
        "RUN11_STP_GATE_OBSERVED_STATES": (
            "LIS -> LRN -> UNOBSERVABLE -> LRN -> UNOBSERVABLE -> FORWARDING"
        ),
        "RUN11_STP_AUTHORITY_TRANSITIONS": (
            "LIS(AUTHORITATIVE) -> LRN(AUTHORITATIVE) -> "
            "UNOBSERVABLE(COMPLETENESS) -> LRN(AUTHORITATIVE) -> "
            "UNOBSERVABLE(COMPLETENESS) -> FORWARDING(AUTHORITATIVE)"
        ),
        "RUN11_STP_FAILURE_DIMENSIONS": "COMPLETENESS",
        "RUN11_STP_GATE_DURATION_MS": "30327",
        "RUN11_STP_GATE_SAMPLES": "15",
        "RUN11_AUTHORITATIVE_FWD_OBSERVED": "YES",
        "RUN11_TRUNK_ALLOWED_VLANS": "(930, 931)",
        "RUN11_TRUNK_ACTIVE_VLANS": "(930, 931)",
        "RUN11_TRUNK_FORWARDING_VLANS": "(930, 931)",
        "RUN11_TRUNK_READ_AUTHORITY": "AUTHORITATIVE",
        "RUN11_CONTROL_DHCP_PRE": "YES",
        "RUN11_INTERVENTION_DHCP_PRE": "YES",
        "RUN11_CONTROL_ARM_ACCEPTED": "UNOBSERVABLE",
        "RUN11_INTERVENTION_ARM_ACCEPTED": "UNOBSERVABLE",
        "RUN11_CONTROL_DHCP_POST": "UNOBSERVABLE",
        "RUN11_INTERVENTION_DHCP_POST": "UNOBSERVABLE",
        "RUN11_DHCP_FLAG_TRANSITION_VALID": "UNOBSERVABLE",
        "RUN11_ACQUISITION_STARTED": "NO",
        "RUN11_ACQUISITION_BOUNDARY": (
            "ACQUISITION_NOT_STARTED_FRESH_DHCP_TRIGGER_UNPROVEN"
        ),
        "TRUNK_FORWARDING_SEMANTIC_AUDIT": (
            "IOS_STP_FORWARDING_AND_NOT_PRUNED_SET_ON_SHARED_TRUNK"
        ),
        "TRUNK_READ_AUTHORITY_RETENTION": "READY",
        "STP_VS_TRUNK_RELATION": "NOT_ESTABLISHED",
        "RUN14_EXECUTED": "YES",
        "RUN14_SOURCE_HEAD": (
            "3592b73e28024ffe4f94decc829ffd05290bc57a"
        ),
        "RUN14_SOURCE_HEAD_STATUS": (
            "REVERTED_BY_4a5adc69c8f54d1f9807e0988b575cf7d7f1412b"
        ),
        "RUN14_RESULT": "SAME_FAILURE_ACTIVATION_CALL_NOT_ACCEPTED",
        "RUN14_EXPERIMENT": "UNIFORM_BASELINE",
        "RUN14_ARM_INTERFACE": "Vlan1",
        "RUN14_ARM_ACCEPTED": "NO_FOR_BOTH_PHONES",
        "RUN14_ARM_ERRORS": (
            "endpoint_dhcp_not_accepted:P1 | endpoint_dhcp_not_accepted:P2"
        ),
        "RUN14_ARM_REFUSAL_REASON_INSTRUMENTED": "NO",
        "RUN14_NETWORK_SHAPE": (
            "P1_ACCESS931_VOICE930 | P2_ACCESS931_VOICE930"
        ),
        "RUN14_PRE_ARM_SVI_DHCP": "YES_FOR_BOTH_PHONES",
        "RUN14_PHONE_STP_ROWS": "ABSENT_BEFORE_AND_AFTER",
        "RUN14_FINAL_IPV4": "EMPTY_FOR_BOTH_PHONES",
        "RUN14_VOICE_BINDING_COUNT": "0",
        "RUN14_SCCP": "NOT_REGISTERED_FOR_BOTH_PHONES",
        "RUN14_FIRST_BOUNDARY": "ENDPOINT_ADDRESS_CONTRADICTED",
        "RUN14_WORKSPACE_RESTORED": "YES",
        "RUN14_REALTIME_RESTORED": "YES",
        "RUN14_CLEANUP_ERRORS": "NONE",
        "RUN14_CONTRACT_VALID": (
            "YES_AS_A_BASELINE_ONLY_NOT_AS_AN_INTERVENTION"
        ),
        "RUN14_SHA256": (
            "f44347d0ffb46f380259443ed3455791346d631cd0ec7c8e31ee7365c409089a"
        ),
        "E5_PHONE_DHCP_ACTIVATION_HYPOTHESIS": "REFUTED",
        "E5_PHONE_DHCP_ACTIVATION_REFUTATION_BASIS": (
            "VLAN1_DOWN_ONCE_VOICE_VLAN_SIGNALLED + NO_OFF_STATE_TO_FLIP + "
            "RUN13_VALID_TRANSITION_NO_ADDRESS"
        ),
        "HISTORICAL_E5_PHONE_ADDRESSING_WAS_A_NO_OP": (
            "ESTABLISHED_FROM_6ea254d_MEASUREMENT"
        ),
        "HISTORICAL_POSITIVE_SLICE_WAS_MANUAL": (
            "ESTABLISHED_FROM_2e7f0f5_DOC"
        ),
        "FIRST_SURVIVING_CAUSAL_DIVERGENCE": (
            "SINGLE_EARLY_PHONE_DISCOVER_VERSUS_ACCESS_PORT_STP_CONVERGENCE"
        ),
        "FRESH_DHCP_TRANSACTION_TRIGGER": (
            "STILL_NOT_AVAILABLE_IN_TYPED_RUNTIME"
        ),
        "RUN15_MODE_PREPARED": "EDGE_BEFORE_VOICE_VLAN",
        "RUN15_LEDGER_ROLE": (
            "EDGE_BEFORE_VOICE_VLAN_CAUSAL_INTERVENTION"
        ),
        "RUN15_VARIABLE": (
            "TYPED_EDGE_POLICY_ON_INTERVENTION_PORT_BEFORE_VOICE_VLAN"
        ),
        "RUN15_NETWORK_SHAPE": (
            "P1_ACCESS931_VOICE930 | P2_ACCESS931_VOICE930"
        ),
        "RUN15_DHCP_MUTATIONS": "NONE",
        "RUN15_FOUNDATION_GATE": (
            "SHARED_FOUNDATION_VERIFIED_BEFORE_VOICE_VLAN_REQUIRED"
        ),
        "RUN15_CLOCK_BOUNDARY": (
            "ONE_SHARED_VOICE_VLAN_BATCH_FOR_BOTH_PORTS"
        ),
        "RUN15_GATE_QUERY_COUNT_PER_SAMPLE": "ONE_SHARED_BY_BOTH_PORTS",
        "RUN15_MILESTONES": (
            "IMMEDIATELY_AFTER_VOICE_VLAN | FIRST_AUTHORITATIVE_STP_SAMPLE | "
            "AUTHORITATIVE_FWD | END_OF_ACQUISITION_WINDOW"
        ),
        "RUN15_EXECUTED": "YES",
        "RUN15_SOURCE_HEAD": (
            "703d5cc989d7f30dc9586b1be9ea7c9c6b1b20e8"
        ),
        "RUN15_RESULT": (
            "FAILED_CLOSED_SHARED_FOUNDATION_UNREADY_BEFORE_ANY_VOICE_VLAN"
        ),
        "RUN15_ACQUISITION_STARTED": "NO",
        "RUN15_ACQUISITION_BOUNDARY": (
            "ACQUISITION_NOT_STARTED_SHARED_FOUNDATION_UNREADY"
        ),
        "RUN15_SHARED_FOUNDATION_READY": "CONTRADICTED",
        "RUN15_BLOCKING_DIMENSION": "TRUNK_FORWARDING_VOICE",
        "RUN15_TRUNK_FORWARDING_VLANS": (
            "EMPTY_WHILE_ALLOWED_AND_ACTIVE_ARE_930_931"
        ),
        "RUN15_EDGE_POLICY_DISPATCH": "NOT_APPLIED",
        "RUN15_VOICE_VLAN_SIGNALLED": "NO",
        "RUN15_PAIRED_STP_GATES": "NOT_REACHED",
        "RUN15_SVI_MILESTONES_RETAINED": "0",
        "RUN15_DHCP_MUTATIONS_OBSERVED": "NONE",
        "RUN15_STP_TIMING_CONTROLS_DHCP_ACQUISITION": "NOT_ESTABLISHED",
        "RUN15_WORKSPACE_RESTORED": "YES",
        "RUN15_REALTIME_RESTORED": "YES",
        "RUN15_CLEANUP_ERRORS": "NONE",
        "RUN15_CONTRACT_VALID": (
            "YES_THE_GATE_REFUSED_TO_TEST_AN_UNCONVERGED_NETWORK"
        ),
        "RUN15_HYPOTHESIS_TESTED": "NO",
        "RUN15_SHA256": (
            "fbec0e7175b5516ca960e99ec543c6888882ab72732773b989bf8f0443e89f08"
        ),
        "RUN15_DEFECT_FOR_NEXT_RUN": (
            "FOUNDATION_READINESS_IS_ONE_INSTANT_SAMPLE_WITH_NO_BOUNDED_WAIT"
        ),
        "TRUNK_FORWARDING_IS_TIME_DEPENDENT": (
            "STRONGLY_SUGGESTED_BY_RUN15_VERSUS_RUN11_TO_RUN14"
        ),
        "RUN16_MODE_PREPARED": "EDGE_BEFORE_VOICE_VLAN",
        "RUN16_FOUNDATION_WAIT": (
            "BOUNDED_VERIFIED_OR_TIMEOUT_BEFORE_EDGE_OR_VOICE_SIGNAL"
        ),
        "RUN16_JOURNAL_SEMANTICS": (
            "INITIAL_VOICE_VLAN_WITHHELD_SINGLE_LATER_APPLICATION_BOUNDARY"
        ),
        "RUN16_CLOCK_ORIGIN": "ONE_SHARED_VOICE_VLAN_BATCH",
        "RUN16_LEDGER_ROLE": (
            "RUN16_EDGE_BEFORE_VOICE_VLAN_CAUSAL_INTERVENTION"
        ),
        "RUN16_EXECUTED": "YES",
        "RUN16_SOURCE_HEAD": (
            "c388391ace419094a99d6ae989ac8bcb2c6c6dc3"
        ),
        "RUN16_RESULT": "SHARED_PREPARED_FOUNDATION_ACQUISITION",
        "RUN16_FOUNDATION_CONVERGENCE": "VERIFIED",
        "RUN16_FOUNDATION_SAMPLES": "13",
        "RUN16_FOUNDATION_DURATION_MS": "31360",
        "RUN16_FOUNDATION_FIRST_VERIFIED_MS": "31360",
        "TRUNK_FORWARDING_CONVERGENCE": "DIRECTLY_OBSERVED",
        "RUN16_TRUNK_FORWARDING_TRANSITION": "EMPTY -> (930, 931)",
        "RUN16_CONTROL_EDGE_DISPATCH": "NOT_APPLIED",
        "RUN16_INTERVENTION_EDGE_DISPATCH": "APPLIED",
        "RUN16_INTERVENTION_EDGE_RUNTIME_STATE": "UNOBSERVABLE",
        "RUN16_VOICE_VLAN_CLOCK_BOUNDARY": (
            "ONE_SHARED_BATCH_APPLIED_SEQUENCE_69"
        ),
        "RUN16_CONTROL_FIRST_STP_STATE": "LIS",
        "RUN16_CONTROL_STP_SEQUENCE": (
            "LIS -> UNOBSERVABLE(COMPLETENESS) -> LIS -> LRN -> FORWARDING"
        ),
        "RUN16_CONTROL_TIME_TO_FWD_MS": "30782",
        "RUN16_INTERVENTION_FIRST_STP_STATE": "LIS",
        "RUN16_INTERVENTION_STP_SEQUENCE": (
            "LIS -> UNOBSERVABLE(COMPLETENESS) -> LIS -> LRN -> FORWARDING"
        ),
        "RUN16_INTERVENTION_TIME_TO_FWD_MS": "30782",
        "RUN16_CONTROL_FINAL_IPV4": "10.93.0.11",
        "RUN16_INTERVENTION_FINAL_IPV4": "10.93.0.10",
        "RUN16_VOICE_BINDING_COUNT": "2",
        "RUN16_CONTROL_MATCHING_BINDING": "YES",
        "RUN16_INTERVENTION_MATCHING_BINDING": "YES",
        "RUN16_CONTROL_SCCP": "REGISTERED",
        "RUN16_INTERVENTION_SCCP": "REGISTERED",
        "RUN16_STP_TIMING_CONTROLS_DHCP_ACQUISITION": "NOT_ESTABLISHED",
        "RUN16_SHA256": (
            "d65a6e79e3d97fea707a42b27139f65b9b8dff8eaf8f9c3e495591a6b34f4563"
        ),
        "MODERN_FAILURE_VOICE_SIGNAL_ORDER": (
            "VOICE_VLAN_BEFORE_TRUNK_FORWARDING_AND_BEFORE_L3_POOL_CME"
        ),
        "MODERN_SUCCESS_VOICE_SIGNAL_ORDER": (
            "L3_POOL_CME_AND_TRUNK_FORWARDING_BEFORE_VOICE_VLAN"
        ),
        "FIRST_BEHAVIORAL_DIVERGENCE": (
            "INITIAL_ACCESS_ACTION_SIGNALS_VOICE_VLAN_VS_WITHHOLDS_IT"
        ),
        "FIRST_CAUSAL_DIVERGENCE": (
            "REGISTRATION_START_BEFORE_POST_SIGNAL_PHONE_ACCESS_FWD"
        ),
        "RUN17_MODE_PREPARED": "TRUNK_FORWARDING_BEFORE_VOICE",
        "RUN17_CONTROL_PRECONDITION": (
            "ALL_READABLE_NONFORWARDING_FOUNDATION_VERIFIED"
        ),
        "RUN17_CONTROL_SIGNAL_BRACKET": (
            "SAME_AUTHORITATIVE_TRUNK_NOT_FORWARDING_BEFORE_AND_AFTER"
        ),
        "RUN17_INTERVENTION_PRECONDITION": (
            "SAME_TRUNK_FORWARDING_VERIFIED"
        ),
        "RUN17_NONVARIABLES": (
            "TOPOLOGY_ACCESS_VLAN_L3_POOL_OPTION150_CME_PORTFAST_DHCP_FLAG"
        ),
        "RUN17_ROLE_SWAP_PREPARED": "YES",
        "RUN17_EXECUTED": "YES",
        "RUN17_SOURCE_HEAD": (
            "4fe86259d34f53e87c0b12599883c291ef294973"
        ),
        "RUN17_RESULT": "TRUNK_FORWARDING_BEFORE_VOICE_NO_EFFECT",
        "RUN17_PRE_CONTROL_FOUNDATION": (
            "VERIFIED_EXCEPT_TRUNK_FORWARDING"
        ),
        "RUN17_TRUNK_FORWARDING_TRANSITION": "EMPTY -> (930, 931)",
        "RUN17_FOUNDATION_WAIT_SAMPLES": "13",
        "RUN17_FOUNDATION_WAIT_MS": "30562",
        "RUN17_CONTROL_FINAL_IPV4": "10.93.0.11",
        "RUN17_INTERVENTION_FINAL_IPV4": "10.93.0.10",
        "RUN17_VOICE_BINDING_COUNT": "2",
        "RUN17_CONTROL_SCCP": "REGISTERED",
        "RUN17_INTERVENTION_SCCP": "REGISTERED",
        "RUN17_SHA256": (
            "c8c627e34739981545061bd97bdf429337e12593631a784a2176d54bc4a55e1f"
        ),
        "RUN17_WORKSPACE_RESTORED": "YES",
        "RUN17_REALTIME_RESTORED": "YES",
        "TRUNK_FORWARDING_AT_SIGNAL_CAUSE": "REFUTED",
        "RUN18_MODE_PREPARED": "VOICE_BOOTSTRAP_BEFORE_SIGNAL",
        "RUN18_CONTROL_BOUNDARY": (
            "NETWORK_READY_BOOTSTRAP_NOT_DISPATCHED"
        ),
        "RUN18_INTERVENTION_BOUNDARY": (
            "SAME_NETWORK_BOOTSTRAP_DISPATCHED"
        ),
        "RUN18_NONVARIABLES": (
            "TOPOLOGY_ACCESS_VLAN_L2_L3_DHCP_TRUNK_PORTFAST_DHCP_FLAG"
        ),
        "RUN18_ROLE_SWAP_PREPARED": "YES",
        "RUN18_EXECUTED": "YES",
        "RUN18_SOURCE_HEAD": (
            "0de600f5629cfc4bb698e0d4e53b1db7bcc8104d"
        ),
        "RUN18_RESULT": "VOICE_BOOTSTRAP_BEFORE_SIGNAL_INSUFFICIENT",
        "RUN18_BOOTSTRAP_WAIT_SAMPLES": "1",
        "RUN18_BOOTSTRAP_WAIT_MS": "391",
        "RUN18_CONTROL_FINAL_IPV4": "EMPTY",
        "RUN18_INTERVENTION_FINAL_IPV4": "EMPTY",
        "RUN18_VOICE_BINDING_COUNT": "0",
        "RUN18_CONTROL_SCCP": "NOT_REGISTERED",
        "RUN18_INTERVENTION_SCCP": "NOT_REGISTERED",
        "RUN18_SVI_AT_AUTHORITATIVE_FWD": "ABSENT_FOR_BOTH",
        "RUN18_SVI_AT_WINDOW_END": (
            "PRESENT_DHCP_YES_IPV4_EMPTY_FOR_BOTH"
        ),
        "RUN18_SHA256": (
            "8528d3126f9b0233b5bbde582c82cbde13bccb5428e24b20a87d3309a1ff48e3"
        ),
        "RUN18_WORKSPACE_RESTORED": "YES",
        "RUN18_REALTIME_RESTORED": "YES",
        "VOICE_BOOTSTRAP_AT_SIGNAL_CAUSE": "REFUTED_AS_SUFFICIENT",
        "RUN19_MODE_PREPARED": (
            "DATA_ACCESS_PREPARATION_BEFORE_VOICE"
        ),
        "RUN19_CONTROL_ACCESS_PREPARATION": "NOT_APPLIED",
        "RUN19_INTERVENTION_ACCESS_PREPARATION": "APPLIED_DATA_ONLY",
        "RUN19_CONTROL_ACCESS_READBACK": "DATA931_CONTRADICTED",
        "RUN19_INTERVENTION_ACCESS_READBACK": "DATA931_VERIFIED",
        "RUN19_VOICE_SIGNAL_BOUNDARY": (
            "ONE_SHARED_DATA_AND_VOICE_BATCH"
        ),
        "RUN19_FOUNDATION_GATE": "SHARED_FOUNDATION_VERIFIED",
        "RUN19_NONVARIABLES": (
            "PHONE_AGE_SIGNAL_TIME_TOPOLOGY_L2_L3_DHCP_BOOTSTRAP_TRUNK_PORTFAST"
        ),
        "RUN19_ROLE_SWAP_PREPARED": "YES",
        "RUN19_EXECUTED": "YES",
        "RUN19_SOURCE_HEAD": (
            "8fdc6ed038d87a8ee1b25408f5e62ec6af2ab63d"
        ),
        "RUN19_RESULT": "DATA_ACCESS_PREPARATION_NO_EFFECT",
        "RUN19_FOUNDATION_WAIT_SAMPLES": "13",
        "RUN19_FOUNDATION_WAIT_MS": "31000",
        "RUN19_CONTROL_FINAL_IPV4": "10.93.0.11",
        "RUN19_INTERVENTION_FINAL_IPV4": "10.93.0.10",
        "RUN19_VOICE_BINDING_COUNT": "2",
        "RUN19_CONTROL_SCCP": "REGISTERED",
        "RUN19_INTERVENTION_SCCP": "REGISTERED",
        "RUN19_SHA256": (
            "49f828acd544b3e82adb4d938629e791feec024d6dd6f6fa239c24c4ac14fcba"
        ),
        "RUN19_WORKSPACE_RESTORED": "YES",
        "RUN19_REALTIME_RESTORED": "YES",
        "DATA_ACCESS_PREPARATION_CAUSE": "REFUTED",
        "VOICE_ROOT_CAUSE": "CONFIRMED",
        "UNOBSERVED_INTERNAL_MECHANISM": (
            "PHONE_BOOT_DHCP_ATTEMPT_AND_RETRY_TIMING"
        ),
        "CORRECTION_IMPLEMENTED": "YES",
        "CORRECTION_ARCHITECTURAL_LEVEL": "DEPENDENCY_AND_CONVERGENCE",
        "RUN20_MODE": "NO_FLAG_PRODUCTION_PIPELINE",
        "RUN20_EXPERIMENT_FLAGS": "NONE",
        "RUN20_PRODUCTION_BARRIER_REQUIRED": "YES",
        "RUN20_EXECUTED": "YES",
        "RUN20_SOURCE_HEAD": (
            "d12e838215226cecfbdba60ea7b9eb4b347ee59c"
        ),
        "RUN20_RESULT": "SAME_FAILURE_NETWORK_GATE_INSUFFICIENT",
        "RUN20_NETWORK_FOUNDATION_STATUS": "VERIFIED",
        "RUN20_VOICE_SIGNAL_STATUS": "VERIFIED",
        "RUN20_CONFIGURATION_STATUS": (
            "PARTIAL_OBSERVABILITY_LIMITATION"
        ),
        "RUN20_FINAL_IPV4": "EMPTY_FOR_BOTH",
        "RUN20_VOICE_BINDING_COUNT": "0",
        "RUN20_SCCP": "NOT_REGISTERED_FOR_BOTH",
        "RUN20_SHA256": (
            "0cc73ff59cc2724274a23886843b814e0ec4f8d9e82fd72c7bc0e234cee7148a"
        ),
        "RUN20_WORKSPACE_RESTORED": "YES",
        "RUN20_REALTIME_RESTORED": "YES",
        "NETWORK_CONVERGENCE_ONLY_FIX": "REFUTED_AS_SUFFICIENT",
        "RUN21_MODE": "NO_FLAG_PRODUCTION_CROSS_STAGE_PIPELINE",
        "RUN21_ORDER": (
            "DATA_ONLY_ACCESS -> NETWORK_VERIFIED -> "
            "VOICE_BOOTSTRAP_APPLIED -> VOICE_SIGNAL_VERIFIED -> REGISTRATION"
        ),
        "RUN21_EXPERIMENT_FLAGS": "NONE",
        "RUN21_EXECUTED": "YES",
        "RUN21_SOURCE_HEAD": (
            "a71632231070d4e869536592fa735af3959d79b6"
        ),
        "RUN21_RESULT": "HARNESS_BOUNDARY_REDUNDANT_ENDPOINT_ARM",
        "RUN21_NETWORK_FOUNDATION_STATUS": "VERIFIED",
        "RUN21_VOICE_SIGNAL_STATUS": "VERIFIED",
        "RUN21_ENDPOINT_DHCP_ARM": "APPLIED_FOR_BOTH",
        "RUN21_FINAL_IPV4": "EMPTY_FOR_BOTH",
        "RUN21_VOICE_BINDING_COUNT": "0",
        "RUN21_SCCP": "NOT_REGISTERED_FOR_BOTH",
        "RUN21_SHA256": (
            "357fda6e6eb5f0ede48f91d3960986fb1ff8a6acf00b3021ec096b22798f1e86"
        ),
        "RUN21_WORKSPACE_RESTORED": "YES",
        "RUN21_REALTIME_RESTORED": "YES",
        "RUN21_PRODUCTION_QUESTION_TESTED": "NO",
        "RUN22_MODE": "NO_FLAG_PRODUCTION_CROSS_STAGE_NO_ENDPOINT_ARM",
        "RUN22_EXPERIMENT_FLAGS": "NONE",
        "RUN22_ENDPOINT_DHCP_ARM": "NOT_APPLICABLE",
        "RUN22_EXECUTED": "YES",
        "RUN22_SOURCE_HEAD": (
            "b842dc1b7530aa9fceb45b4853bc28fdefa34786"
        ),
        "RUN22_RESULT": "SAME_FAILURE_POST_SIGNAL_CONVERGENCE_MISSING",
        "RUN22_NETWORK_FOUNDATION_STATUS": "VERIFIED",
        "RUN22_VOICE_SIGNAL_STATUS": "VERIFIED",
        "RUN22_FINAL_IPV4": "EMPTY_FOR_BOTH",
        "RUN22_VOICE_BINDING_COUNT": "0",
        "RUN22_SCCP": "NOT_REGISTERED_FOR_BOTH",
        "RUN22_SHA256": (
            "fa6147a65c4645cb76da6ec3858539ce82b8ddc1aeef65ed273115b36399a26a"
        ),
        "RUN22_WORKSPACE_RESTORED": "YES",
        "RUN22_REALTIME_RESTORED": "YES",
        "POST_SIGNAL_ACCESS_CONVERGENCE_CAUSE": "CONFIRMED",
        "VOICE_ROOT_CAUSE_CONFIRMED": (
            "REGISTRATION_STARTS_BEFORE_AUTHORITATIVE_PHONE_ACCESS_FORWARDING_"
            "AFTER_LATE_VOICE_SIGNAL"
        ),
        "CORRECTION_SUMMARY": (
            "DATA_ONLY_ACCESS -> NETWORK_VERIFIED -> VOICE_BOOTSTRAP_APPLIED "
            "-> VOICE_SIGNAL_VERIFIED -> PHONE_ACCESS_FWD -> REGISTRATION"
        ),
        "RUN23_MODE": "NO_FLAG_PRODUCTION_COMPLETE_CONVERGENCE_PIPELINE",
        "RUN23_EXPERIMENT_FLAGS": "NONE",
        "RUN23_EXECUTED": "YES",
        "RUN23_SOURCE_HEAD": (
            "852d6abee4d5ae28894e5dfcb33f75400e18b49b"
        ),
        "RUN23_RESULT": "SUCCESS",
        "RUN23_NETWORK_FOUNDATION_STATUS": "VERIFIED",
        "RUN23_VOICE_SIGNAL_STATUS": "VERIFIED",
        "RUN23_PHONE_ACCESS_FORWARDING": "VERIFIED_2_OF_2",
        "RUN23_PHONE_ACCESS_FORWARDING_SAMPLES": "73",
        "RUN23_PHONE_ACCESS_FORWARDING_MS": "31031",
        "RUN23_CONTROL_FINAL_IPV4": "10.93.0.10",
        "RUN23_INTERVENTION_FINAL_IPV4": "10.93.0.11",
        "RUN23_VOICE_BINDING_COUNT": "2",
        "RUN23_CONTROL_MATCHING_BINDING": "YES",
        "RUN23_INTERVENTION_MATCHING_BINDING": "YES",
        "RUN23_CONTROL_SCCP": "REGISTERED",
        "RUN23_INTERVENTION_SCCP": "REGISTERED",
        "RUN23_ENDPOINT_DHCP_ARM": "NOT_APPLICABLE",
        "RUN23_SHA256": (
            "dc74fab6758dcca2b0baef7ec9744c05de12f8e010902031e6e9d5b724224d43"
        ),
        "RUN23_WORKSPACE_RESTORED": "YES",
        "RUN23_REALTIME_RESTORED": "YES",
        "DISPOSABLE_PRODUCTION_STYLE_VERIFICATION": "PASS",
        "PRODUCTION_FIX_JUSTIFIED": "YES",
        "DOES_CP_SCALE_HAVE_THE_SAME_DEFECT": "YES",
        "CP_SCALE_AFFECTED_PHONES": "69",
        "CP_SCALE_AFFECTED_VOICE_ACCESS_ACTIONS": "69",
        "CP_SCALE_TOPOLOGY_REGEN_REQUIRED": "NO",
        "CP_SCALE_CANONICAL_LIVE_RUN": "EXECUTED_SEVENTEEN_TIMES",
        "CANONICAL_CP_SCALE_LIVE_RUN": "EXECUTED_SEVENTEEN_TIMES",
        "CANONICAL_CP_SCALE_LIVE_ATTEMPTS": "17",
        "CANONICAL_CP_SCALE_INVALID_LIVE_ATTEMPTS": "2",
        "CANONICAL_CP_SCALE_BASE_HEAD": (
            "528564493b855ce332f45fdab7b5867a065b1992"
        ),
        "CANONICAL_CP_SCALE_PRELIVE_HEAD": (
            "fe725ac177d2ea452cfd52da6d81994fbd2a894c"
        ),
        "CANONICAL_CP_SCALE_LIVE_SOURCE_HEAD": (
            "fe725ac177d2ea452cfd52da6d81994fbd2a894c"
        ),
        "CANONICAL_CP_SCALE_PHONE_COUNT": "69",
        "CANONICAL_CP_SCALE_VOICE_ACCESS_ACTION_COUNT": "69",
        "CANONICAL_CP_SCALE_STAGE_VOICE_COUNTS": (
            "FLOOR1_21 | FLOOR2_35 | FLOOR3_51 | ROUTER0_62 | ROUTER3_69"
        ),
        "CANONICAL_CP_SCALE_PRODUCTION_PATH": (
            "CONFIRMED_OFFLINE_ALL_STAGES_AND_LIVE_THROUGH_FLOOR1"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_VOICE": (
            "VERIFIED_21_OF_21"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_LAST_COMPLETE_VOICE_WINDOW": (
            "ENDPOINT_AND_BINDING_VERIFIED_21_OF_21 | "
            "SCCP_REGISTERED_21_OF_21"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_PHONE_ACCESS_FWD": (
            "VERIFIED_21_OF_21"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_BINDING_READBACK": (
            "RAW_21 | PARSED_21 | "
            "EPHONE19_HEADER_INDENTATION_ACCEPTED"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_CAPACITY_RESULT": (
            "MAX_EPHONES_51_INVALID | "
            "MAX_EPHONES_42_REFUTED_FOR_ORDINAL_LOSS"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_BINDING_ORDER_RESULT": (
            "INDEX1_REFUTED | "
            "ORDINAL19_WAS_PAGER_BOUNDARY_OBSERVER_ARTIFACT"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_CME_MODE_RESULT": (
            "AUTO_REGISTRATION_REFUTED"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_LAST_COMPLETE_ENDPOINTS": (
            "SVI_21 | DHCP_ENABLED_21 | ADDRESSED_21 | "
            "MATCHING_BINDINGS_21 | SCCP_REGISTERED_21"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_LAST_COMPLETE_MISSING_RAW_EPHONE_EXTENSIONS": (
            "NONE"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_CONFIRMED_OBSERVER_DEFECT": (
            "EPHONE7_IP_INDENTATION | EPHONE19_HEADER_INDENTATION"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_LAST_COMPLETE_BOUNDARY": "SCCP",
        "CANONICAL_CP_SCALE_FLOOR1_CURRENT_BOUNDARY": (
            "NONE_VERIFIED"
        ),
        "CANONICAL_CP_SCALE_PRIOR_FLOOR2_NETWORK_FOUNDATION": (
            "FAILED_3_FRESH_TRUNK_CONTRADICTIONS"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_NETWORK_FOUNDATION": (
            "VERIFIED_9_OF_9_TRUNKS"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_OFFLINE_DIAGNOSIS": "COMPLETE",
        "CANONICAL_CP_SCALE_FLOOR2_PRIOR_STAGE_SEMANTICS": (
            "CUMULATIVE_REPLAY"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_ACTIONS_REAPPLIED_AT_FAILED_FLOOR2": (
            "115_OF_115"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_NEW_CONFIGURATION_ACTIONS": "76",
        "CANONICAL_CP_SCALE_FLOOR2_FIRST_SOURCE_DIVERGENCE": (
            "CUMULATIVE_CONFIGURATION_VIEW_USED_AS_PERSISTENT_WORKSPACE_"
            "MUTATION_SET"
        ),
        "CANONICAL_CP_SCALE_FLOOR1_OBSERVED_STP_ROOT": (
            "SWITCH5_NATURAL_ROOT_VLANS_10_20_30_BASE_PRIORITY_32768"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_LARGE_SITE_STP_POLICY": (
            "WITHHELD_UNTIL_FLOOR3"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_FAILED_RUN_TEMPORAL_EVIDENCE": (
            "FRESH_BOUNDARY_LRN_THEN_ATOMIC_REFRESH_FWD"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_TIMEOUT_CLASSIFICATION": (
            "CONFIRMED_FIXED_BOUNDARY_EXPIRED_DURING_PVST_CONVERGENCE"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_NETWORK_ROOT_CAUSE": "CONFIRMED",
        "CANONICAL_CP_SCALE_FLOOR2_ROOT_CAUSE_CANDIDATES": (
            "RESOLVED_CUMULATIVE_REPLAY_CONTRIBUTOR_PLUS_PVST_BOUNDARY"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_PRODUCT_FIX": (
            "VERIFIED_DELTA_ONLY_PLUS_FRESH_PVST_BOUNDARY_ATOMIC_REFRESH"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_CAUSAL_IMPLEMENTATION_HEAD": (
            "ff1be60f0dad31a17fdb44d27834d251e2927732"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_CONFIGURATION_MUTATION": (
            "DELTA_ONLY_76_NEW_ACTIONS"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_CONFIGURATION_VERIFICATION": (
            "CUMULATIVE_191_EXPECTATIONS_PRESERVED"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_TEMPORAL_OBSERVER": (
            "ROUND_ROBIN_TRUNK_TRANSITIONS_PLUS_CORRELATED_PVST_BOUNDARIES"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_CAUSAL_LIVE": (
            "VERIFIED_NETWORK_FOUNDATION | BOUNDARY_LRN | "
            "REFRESH_FWD_9_OF_9 | EXTENSION_NOT_ENGAGED"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_DIAGNOSIS_DOC": (
            "docs/reference/cp-scale/floor2_network_foundation_root_cause.md"
        ),
        "CANONICAL_CP_SCALE_PHONE_ACCESS_GROUPS": (
            "1_VERIFIED | 7_NOT_REACHED"
        ),
        "CANONICAL_CP_SCALE_PHONE_ACCESS_FWD": (
            "EXPECTED_69 | VERIFIED_21 | FAILED_0 | UNOBSERVABLE_0 | "
            "NOT_REACHED_48"
        ),
        "CANONICAL_CP_SCALE_REGISTRATION_AFTER_FWD_BARRIER": (
            "YES_FLOOR1 | NOT_ESTABLISHED_LATER_STAGES"
        ),
        "CANONICAL_CP_SCALE_NOT_REACHED_PHONES": "48",
        "CANONICAL_CP_SCALE_FIRST_CONTRADICTED_BOUNDARY": (
            "FLOOR2_VOICE_BOOTSTRAP_RETAINED_BINDING_READBACK"
        ),
        "CANONICAL_CP_SCALE_FAILURE_CLASSIFICATION": (
            "PRODUCT_STAGE_REPLAY_PLUS_OBSERVER"
        ),
        "CANONICAL_CP_SCALE_VOICE_VERIFICATION": "FAIL",
        "ROOT_CAUSE_STATUS": "CONFIRMED",
        "PRODUCTION_FIX_STATUS": (
            "FLOOR2_VOICE_DELTA_ONLY_IMPLEMENTED_LIVE_PENDING"
        ),
        "CANONICAL_CP_SCALE_SCCP_DIAGNOSTIC_HEAD": (
            "bd8e8b80bd170704e3f403263186f0469a4d0839"
        ),
        "CANONICAL_CP_SCALE_EPHONE_CAUSAL_CORRECTION_HEAD": (
            "dcb156753bce9c5b4559e5c1dc8db6ac323a8f72"
        ),
        "CANONICAL_CP_SCALE_BINDING_READBACK_GATE_HEAD": (
            "a97e645e479ff72377b8775d3f634e291c507307"
        ),
        "CANONICAL_CP_SCALE_BINDING_PAGER_OBSERVER_HEAD": (
            "7d694309ac75df2d3605ce35f5f892279d794aa1"
        ),
        "CANONICAL_CP_SCALE_SEMANTIC_BINDING_ORDER_HEAD": (
            "6a81a6f47a9b10b5d16de4c89bc87418aad5b7f6"
        ),
        "CANONICAL_CP_SCALE_EXPLICIT_CME_MODE_HEAD": (
            "6fd0a0a69fdd5f9a5054f073ed6534e4a4fc7ee8"
        ),
        "CANONICAL_CP_SCALE_ABSENCE_RECONCILIATION_HEAD": (
            "a9115cdd65fe467bf54968b1d86c5e6dbcec1aca"
        ),
        "CANONICAL_CP_SCALE_DEFERRED_FRONTIER_RECONCILIATION_HEAD": (
            "e0e4f8848404ea7d48feedb5d52fb0d0c1cfdf8c"
        ),
        "CANONICAL_CP_SCALE_FINAL_SITE_CAPACITY_HEAD": (
            "942f35716d04d89e7f59fbb57bf654dd04bc5e58"
        ),
        "CANONICAL_CP_SCALE_GOVERNED_CAPACITY_MODEL_HEAD": (
            "e83ae0c431c18b5c6e24bcd424a08c5b45d0270d"
        ),
        "CANONICAL_CP_SCALE_BINDING_TERMINAL_DIAGNOSTIC_HEAD": (
            "71715ed2edcb4a306a0537a4e97c1991e503b38a"
        ),
        "CANONICAL_CP_SCALE_EPHONE_HEADER_PARSER_CORRECTION_HEAD": (
            "368931c517755766fe69cbda557b85aa25fda6a8"
        ),
        "CANONICAL_CP_SCALE_EPHONE_HEADER_PARSER_CORRECTION": (
            "VERIFIED_CANONICAL_FLOOR1_21_OF_21"
        ),
        "CANONICAL_CP_SCALE_CHECKPOINT_EOF_SOURCE_HEAD": (
            "3c74547c50eba2dfdd0e1ac62a8da696b4ca6934"
        ),
        "CANONICAL_CP_SCALE_CHECKPOINT_COMMAND_CHANNEL": (
            "EOF_BEFORE_OPERATOR_COMMAND"
        ),
        "CANONICAL_CP_SCALE_NEXT_CHECKPOINT_TRANSPORT": (
            "PERSISTENT_STDIN_WITH_NINE_TYPED_CONTINUE_COMMANDS"
        ),
        "CANONICAL_CP_SCALE_RIP_PAGER_RETRY_HEAD": (
            "6bf0b8e3a5dbd6899226c1eaaf04ef2011c69b89"
        ),
        "CANONICAL_CP_SCALE_RIP_PAGER_RETRY_LATEST": (
            "NOT_ENGAGED_FIRST_READS_VERIFIED"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_PVST_BOUNDARY_GATE_HEAD": (
            "e57d37d1e75890f08a208aaea9f8c1a36d8b0063"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_PVST_BOUNDARY_GATE": (
            "VERIFIED_ATOMIC_REFRESH_NO_EXTENSION"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_VOICE_MUTATION_PREVIOUS": (
            "CUMULATIVE_75_REPLAYED"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_VOICE_FIRST_FAILURE": (
            "RETAINED_FLOOR1_BINDING_1_PAGER_UNOBSERVABLE_2_OF_2"
        ),
        "CANONICAL_CP_SCALE_FLOOR2_VOICE_DELTA": (
            "MUTATE_29_RETAIN_46_VERIFY_35"
        ),
        "CANONICAL_CP_SCALE_CONTROL_PLANE_DELTA": (
            "ROUTING_CORE_3 | ROUTER4_SWITCH10_0 | FLOOR1_0 | FLOOR2_0 | "
            "FLOOR3_166 | ROUTER0_31 | ROUTER3_17 | FULL_0"
        ),
        "CANONICAL_CP_SCALE_FINAL_QUALIFICATION_MUTATION": (
            "CONFIGURATION_0 | VOICE_0 | CONTROL_PLANE_0"
        ),
        "CANONICAL_CP_SCALE_FINAL_VOICE_QUALIFICATION": (
            "RETAINED_SIGNAL_FRESH_DIRECT_FWD_REGISTRATION"
        ),
        "CANONICAL_CP_SCALE_CALL_FAILURE_GATE": (
            "EXACT_INVENTORY | FAILED_CALL_CONTRADICTS | "
            "UNOBSERVABLE_REMAINS_BOUNDED"
        ),
        "CANONICAL_CP_SCALE_EVIDENCE_SHA256": (
            "RUN1_PRECLEANUP_"
            "d4b017332c1f0b7f12e5e6fef977a508c7b1fcdb72e1f605ad095143b54a60db"
            " | RUN1_CLEANUP_"
            "a066f7efbedc23176871e2c0a75e3e2422426554dbb2aad3a9126e6e06e759db"
            " | RUN2_PRECLEANUP_"
            "6662ffa03e405645882d4d61bcbcec3af60957e4dac64d881bebd9fa15590c03"
            " | RUN2_CLEANUP_"
            "968face019bad5adb4f5890d4a6f15b3164d143d3eff609df40622bb4ce4ec7a"
            " | RUN3_PRECLEANUP_"
            "28a9bbefb5e9a5c3c4dec0a5fbbaec3690b0e9ebfd06bd1b842814cb0fca7fea"
            " | RUN3_CLEANUP_"
            "a6899f944fec58f6ae187d67c8350ad82b1ec9a94aa84d0ba7dd13177b7b2670"
            " | RUN4_PRECLEANUP_"
            "384188e7067a94495c4de5a99ff523909d2239567f453435b1c6e12fe4438218"
            " | RUN4_CLEANUP_"
            "76d1ec861384db9d01e53987092fc15a87cb001c0e3124deeeaea7fa492ec24a"
            " | RUN5_PRECLEANUP_"
            "36648e37b859d11c77ceae95afef33b972048e65928a90cf7a8cdf76c04b96be"
            " | RUN5_CLEANUP_"
            "744639c0833702c55ad47fec6df13312f1adac2706f832e0a141a9978bab6fea"
            " | RUN6_PRECLEANUP_"
            "698f8f3e5358ab85286432262d7fda89f30da5cf87a3e619c471ab50cb4d055c"
            " | RUN6_CLEANUP_"
            "28f8f200a44251d45ebc89a4b1261c11615b66613526665ae626b241537e690d"
            " | RUN7_PRECLEANUP_"
            "21a306f9c1d4f2955f443c1192bb0e65093bdbee2bca37f1fd1dddeafe3bcd62"
            " | RUN7_CLEANUP_"
            "65923bc0a708f1481087922eaea8e1baff9debddb0f845a9b02db7e2942eb261"
            " | RUN8_PRECLEANUP_"
            "05bda710dad7e15b381013510d016a94f3f9071410250f341542b3ea36c5b06c"
            " | RUN8_CLEANUP_"
            "1cf0c9fb80e25780bbb64a91553c52dac63abcad853926bc8d450d61907e168f"
            " | RUN9_PRECLEANUP_"
            "a0d663dc00a9bb69437616717dfe702f08f260272b362a629dc1af32fd3f6572"
            " | RUN9_CLEANUP_"
            "a221fdb51d18727f0c7635daddd1397e0c2f01390923996b78c8e2b3fd54aabc"
            " | RUN10_PRECLEANUP_"
            "d60b09f81f6eeebedc0651dd92cc2c0686c2fa29f0c764dfbc0ced15ecb1fc71"
            " | RUN10_CLEANUP_"
            "ac8db8bf21f06837a1ad44a6edc3a4efd03e8c1d0ba27c93d439c96c95e72723"
            " | RUN11_PRECLEANUP_"
            "1c38c536b0735788fa5108ce976b8385afae7d5086ba99ad9dcefdde20edbc78"
            " | RUN11_CLEANUP_"
            "ce890a1e0364b232c9030a4731255f706559c1832f044637cc00db97ea6703aa"
            " | RUN12_PRECLEANUP_"
            "6d893e1fdd6b403f60d1741b0ce7d537712f1128cff1f03a11c7d74bb36e3d65"
            " | RUN12_CLEANUP_"
            "d8eac70ef48373c30eb735764d9a16d7048ea0c1298b71473f481d274bff0aef"
            " | RUN13_PRECLEANUP_"
            "0410c1b7a43fa2290427c78255b8bfcce84d4a833da1f2cde476fcc865a91b18"
            " | RUN13_CLEANUP_"
            "4a8b86945e237f9cd7190d22aa11205c25aed49639e13bc900d766320ade34df"
            " | RUN14_PRECLEANUP_"
            "e272e64c5afef82114b8f750017890ae9e07970de4e6922c9e9533549a4b82d1"
            " | RUN14_CLEANUP_"
            "a36a2dda5f1ef1037385d176f971dabd8d257e37d1b8f1b3d6183cc1ae0dc1d2"
            " | RUN15_PRECLEANUP_"
            "8a3976a64d36fa86e4030a52dae336936734840c691e2489e60db03205fb9d19"
            " | RUN15_CLEANUP_"
            "dfd63b75ebcb7c5c8fa0d408c558bd98f10a8ef69db83684235c3d4636f065df"
            " | RUN16_PRECLEANUP_"
            "4e93efde1bef8053062390fb46914f455791f948c64cce7167c09502d63d3212"
            " | RUN16_CLEANUP_"
            "75d2a740df86d3470aadd316606e915d648112f648a66e8f7fb7ebd3208b74f1"
            " | RUN17_PRECLEANUP_"
            "74646adf4be2c49a512291d37873219001e5ffa5720d33d77fa680b64b00c09d"
            " | RUN17_CLEANUP_"
            "940d900f6b37690e0d59b0a532d728001f1828b9e4446157d9f5ef53ca3647ea"
        ),
        "CANONICAL_CP_SCALE_WORKSPACE_RESTORED": "YES",
        "CANONICAL_CP_SCALE_REALTIME_RESTORED": "YES",
        "LIVE_RUNS_CONSUMED": "23",
        "CLEANUP": "VERIFIED_AFTER_EVERY_LIVE",
        "WORKSPACE_RESTORED": "YES",
        "NEXT_ACTIVE_STEP": (
            "RUN_CANONICAL_LIVE_WITH_DELTA_ONLY_CUMULATIVE_VOICE"
        ),
        "CP_SCALE_STATUS": (
            "FLOOR2_NETWORK_VERIFIED_VOICE_DELTA_LIVE_PENDING"
        ),
    }

    actual = parse_handoff_state(handoff)

    assert actual == expected
