"""Effect boundaries consumed by the CP-SCALE coordinator."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from .checkpoint import CPScaleCheckpointDecision, CPScaleCheckpointPrepared, CPScaleCheckpointResumption

from .contracts import CPScaleLiveRequest, CPScalePreflightResult, CPScaleStageExecutionInput, CPScaleLiveStageResult
from .run_contracts import CPScaleRunReport, CPScaleCleanupAttestation, CPScaleTerminalEvent
from ..use_cases.qualify_cp_scale_live import CPScaleEvidenceArchive


class CPScalePreflightPort(Protocol):
    def inspect(self, request: CPScaleLiveRequest, *, run_identity: str, started_at: datetime) -> CPScalePreflightResult: ...


class CPScaleStageExecutorPort(Protocol):
    def execute(self, request: CPScaleStageExecutionInput) -> CPScaleLiveStageResult: ...


class CPScaleEvidencePort(Protocol):
    def write_progress(self, report: CPScaleRunReport) -> None: ...
    def checkpoint(self, stage: str, report: CPScaleRunReport, *, final: bool = False) -> None: ...
    def archive(self, phase: str, payload: CPScaleRunReport | CPScaleCleanupAttestation, *, run_identity: str) -> CPScaleEvidenceArchive: ...


class CPScaleCheckpointPort(Protocol):
    def prepare(self, stage: str) -> CPScaleCheckpointPrepared: ...
    def publish_and_prompt(self, prepared: CPScaleCheckpointPrepared, publication: CPScaleRunReport) -> CPScaleCheckpointDecision: ...
    def resume(self, session_source_head: str) -> CPScaleCheckpointResumption: ...
    def publish_resumed(self, resumed: CPScaleCheckpointResumption, publication: CPScaleRunReport) -> None: ...


class CPScalePresentationPort(Protocol):
    def core_rematerialized(self) -> None: ...
    def terminal(self, event: CPScaleTerminalEvent, report: CPScaleRunReport) -> None: ...
    def finalization_incomplete(self, report: CPScaleRunReport) -> None: ...
