"""
Taxonomía de errores del sistema.

Cada error tiene un código, mensaje y sugerencia para que el LLM
pueda entender qué falló y cómo corregirlo automáticamente.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum


class ErrorCode(str, Enum):
    # Dispositivos
    UNKNOWN_DEVICE_MODEL = "UNKNOWN_DEVICE_MODEL"
    DUPLICATE_DEVICE_NAME = "DUPLICATE_DEVICE_NAME"
    INSUFFICIENT_PORTS = "INSUFFICIENT_PORTS"

    # Enlaces
    DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
    INVALID_PORT = "INVALID_PORT"
    PORT_ALREADY_USED = "PORT_ALREADY_USED"
    INVALID_CABLE_TYPE = "INVALID_CABLE_TYPE"

    # IPs
    INVALID_IP_ADDRESS = "INVALID_IP_ADDRESS"
    SUBNET_OVERLAP = "SUBNET_OVERLAP"
    IP_CONFLICT = "IP_CONFLICT"

    # DHCP
    DHCP_ROUTER_NOT_FOUND = "DHCP_ROUTER_NOT_FOUND"
    DHCP_GATEWAY_MISMATCH = "DHCP_GATEWAY_MISMATCH"

    # Routing
    UNSUPPORTED_ROUTING_PROTOCOL = "UNSUPPORTED_ROUTING_PROTOCOL"

    # Templates
    TEMPLATE_CONSTRAINT_VIOLATION = "TEMPLATE_CONSTRAINT_VIOLATION"

    # ACL
    ACL_ROUTER_NOT_FOUND = "ACL_ROUTER_NOT_FOUND"
    ACL_INTERFACE_NOT_FOUND = "ACL_INTERFACE_NOT_FOUND"
    ACL_INVALID_NUMBER = "ACL_INVALID_NUMBER"
    ACL_TYPE_MISMATCH = "ACL_TYPE_MISMATCH"
    ACL_DUPLICATE_SEQUENCE = "ACL_DUPLICATE_SEQUENCE"
    ACL_INVALID_WILDCARD = "ACL_INVALID_WILDCARD"
    ACL_INVALID_PROTOCOL_FOR_PORTS = "ACL_INVALID_PROTOCOL_FOR_PORTS"
    ACL_UNREACHABLE_RULE = "ACL_UNREACHABLE_RULE"
    ACL_EMPTY = "ACL_EMPTY"

    # NAT
    NAT_ROUTER_NOT_FOUND = "NAT_ROUTER_NOT_FOUND"
    NAT_INTERFACE_NOT_FOUND = "NAT_INTERFACE_NOT_FOUND"
    NAT_INVALID_IP = "NAT_INVALID_IP"
    NAT_INVALID_NETMASK = "NAT_INVALID_NETMASK"
    NAT_POOL_RANGE_INVALID = "NAT_POOL_RANGE_INVALID"
    NAT_MISSING_INSIDE_NETWORKS = "NAT_MISSING_INSIDE_NETWORKS"
    NAT_MISSING_STATIC_MAPPINGS = "NAT_MISSING_STATIC_MAPPINGS"
    NAT_MISSING_POOL = "NAT_MISSING_POOL"
    NAT_SAME_INTERFACE = "NAT_SAME_INTERFACE"

    # VLAN / trunk / inter-VLAN
    VLAN_INVALID_ID = "VLAN_INVALID_ID"
    VLAN_DUPLICATE_ID = "VLAN_DUPLICATE_ID"
    VLAN_SUBNET_OVERLAP = "VLAN_SUBNET_OVERLAP"
    VLAN_TRUNK_PORT_INVALID = "VLAN_TRUNK_PORT_INVALID"
    VLAN_ROUTER_NOT_FOUND = "VLAN_ROUTER_NOT_FOUND"
    VLAN_SWITCH_NOT_FOUND = "VLAN_SWITCH_NOT_FOUND"
    VLAN_INTERFACE_NOT_FOUND = "VLAN_INTERFACE_NOT_FOUND"

    # STP / port-security
    STP_INVALID_PRIORITY = "STP_INVALID_PRIORITY"
    STP_SWITCH_NOT_FOUND = "STP_SWITCH_NOT_FOUND"
    PORTSEC_SWITCH_NOT_FOUND = "PORTSEC_SWITCH_NOT_FOUND"
    PORTSEC_INVALID_MAC = "PORTSEC_INVALID_MAC"
    PORTSEC_INVALID_MAX = "PORTSEC_INVALID_MAX"

    # Device hardening
    HARDENING_DEVICE_NOT_FOUND = "HARDENING_DEVICE_NOT_FOUND"
    HARDENING_SSH_REQUIRES_DOMAIN = "HARDENING_SSH_REQUIRES_DOMAIN"
    HARDENING_WEAK_MODULUS = "HARDENING_WEAK_MODULUS"
    HARDENING_INVALID_CHARS = "HARDENING_INVALID_CHARS"

    # NetFlow
    NETFLOW_INVALID_NAME = "NETFLOW_INVALID_NAME"
    NETFLOW_INVALID_DESTINATION = "NETFLOW_INVALID_DESTINATION"
    NETFLOW_INVALID_PORT = "NETFLOW_INVALID_PORT"
    NETFLOW_INVALID_VERSION = "NETFLOW_INVALID_VERSION"
    NETFLOW_INCOMPLETE = "NETFLOW_INCOMPLETE"
    NETFLOW_DEVICE_NOT_FOUND = "NETFLOW_DEVICE_NOT_FOUND"
    NETFLOW_PORT_NOT_FOUND = "NETFLOW_PORT_NOT_FOUND"

    # Interface tuning
    IFTUNE_DEVICE_NOT_FOUND = "IFTUNE_DEVICE_NOT_FOUND"
    IFTUNE_INTERFACE_NOT_FOUND = "IFTUNE_INTERFACE_NOT_FOUND"
    IFTUNE_CLOCKRATE_NOT_SERIAL = "IFTUNE_CLOCKRATE_NOT_SERIAL"
    IFTUNE_INVALID_OSPF_AUTH = "IFTUNE_INVALID_OSPF_AUTH"
    IFTUNE_INVALID_OSPF_TIMERS = "IFTUNE_INVALID_OSPF_TIMERS"

    # General
    INVALID_INTERFACE_ASSIGNMENT = "INVALID_INTERFACE_ASSIGNMENT"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Enterprise intent
    ENTERPRISE_INVALID_ENDPOINT_COUNT = "ENTERPRISE_INVALID_ENDPOINT_COUNT"
    ENTERPRISE_INVALID_GROWTH_PERCENT = "ENTERPRISE_INVALID_GROWTH_PERCENT"
    ENTERPRISE_EMPTY_SITE_NAME = "ENTERPRISE_EMPTY_SITE_NAME"
    ENTERPRISE_ADDRESS_SPACE_INVALID = "ENTERPRISE_ADDRESS_SPACE_INVALID"
    SITE_ADDRESS_SPACE_OVERLAP = "SITE_ADDRESS_SPACE_OVERLAP"
    SITE_ADDRESS_SPACE_TOO_SMALL = "SITE_ADDRESS_SPACE_TOO_SMALL"
    SITE_ADDRESS_SPACE_OUTSIDE_ENTERPRISE = "SITE_ADDRESS_SPACE_OUTSIDE_ENTERPRISE"
    SEGMENT_ADDRESS_SPACE_TOO_SMALL = "SEGMENT_ADDRESS_SPACE_TOO_SMALL"
    ENTERPRISE_NO_USABLE_SUBNET = "ENTERPRISE_NO_USABLE_SUBNET"
    ENTERPRISE_DUPLICATE_HIERARCHY_ID = "ENTERPRISE_DUPLICATE_HIERARCHY_ID"
    ENTERPRISE_WAN_MEDIA_CONFLICT = "ENTERPRISE_WAN_MEDIA_CONFLICT"
    ENTERPRISE_WAN_SELF_LINK = "ENTERPRISE_WAN_SELF_LINK"
    ENTERPRISE_WAN_SITE_NOT_FOUND = "ENTERPRISE_WAN_SITE_NOT_FOUND"
    ENTERPRISE_WAN_MEDIA_UNKNOWN = "ENTERPRISE_WAN_MEDIA_UNKNOWN"

    # Enterprise hardware planning
    NO_COMPATIBLE_DEVICE = "NO_COMPATIBLE_DEVICE"
    CAPABILITY_EVIDENCE_REQUIRED = "CAPABILITY_EVIDENCE_REQUIRED"
    INSUFFICIENT_PORT_CAPACITY = "INSUFFICIENT_PORT_CAPACITY"
    INSUFFICIENT_POE_CAPACITY = "INSUFFICIENT_POE_CAPACITY"
    INSUFFICIENT_UPLINK_CAPACITY = "INSUFFICIENT_UPLINK_CAPACITY"
    MODULE_CONFIGURATION_IMPOSSIBLE = "MODULE_CONFIGURATION_IMPOSSIBLE"
    MODULE_SLOT_EXHAUSTED = "MODULE_SLOT_EXHAUSTED"
    PORT_ASSIGNMENT_FAILED = "PORT_ASSIGNMENT_FAILED"
    REDUNDANCY_REQUIREMENT_UNSATISFIED = "REDUNDANCY_REQUIREMENT_UNSATISFIED"

    # Packet Tracer capability discovery
    PROBE_SESSION_FAILED = "PROBE_SESSION_FAILED"
    PROBE_TIMEOUT = "PROBE_TIMEOUT"
    PROBE_CLEANUP_FAILED = "PROBE_CLEANUP_FAILED"
    PROBE_PREREQUISITE_MISSING = "PROBE_PREREQUISITE_MISSING"
    RUNTIME_MODEL_NOT_FOUND = "RUNTIME_MODEL_NOT_FOUND"
    RUNTIME_MODEL_UNCLASSIFIED = "RUNTIME_MODEL_UNCLASSIFIED"
    CAPABILITY_PROBE_FAILED = "CAPABILITY_PROBE_FAILED"
    CAPABILITY_EVIDENCE_CONFLICT = "CAPABILITY_EVIDENCE_CONFLICT"
    CAPABILITY_SNAPSHOT_INVALID = "CAPABILITY_SNAPSHOT_INVALID"
    PACKET_TRACER_VERSION_UNKNOWN = "PACKET_TRACER_VERSION_UNKNOWN"


@dataclass
class PlanError:
    """Error estructurado con código, mensaje y sugerencia de corrección."""
    code: ErrorCode
    message: str
    device: str = ""
    suggestion: str = ""

    def __str__(self) -> str:
        parts = [f"[{self.code.value}]"]
        if self.device:
            parts.append(f"({self.device})")
        parts.append(self.message)
        if self.suggestion:
            parts.append(f"→ Sugerencia: {self.suggestion}")
        return " ".join(parts)

    def to_dict(self) -> dict:
        return {
            "error_code": self.code.value,
            "device": self.device,
            "message": self.message,
            "suggestion": self.suggestion,
        }


@dataclass
class ValidationResult:
    """Resultado completo de una validación."""
    errors: list[PlanError] = field(default_factory=list)
    warnings: list[PlanError] = field(default_factory=list)

    @property
    def is_valid(self) -> bool:
        return len(self.errors) == 0

    def error_messages(self) -> list[str]:
        return [str(e) for e in self.errors]

    def warning_messages(self) -> list[str]:
        return [str(w) for w in self.warnings]

    def to_dict(self) -> dict:
        return {
            "valid": self.is_valid,
            "error_count": len(self.errors),
            "warning_count": len(self.warnings),
            "errors": [e.to_dict() for e in self.errors],
            "warnings": [w.to_dict() for w in self.warnings],
        }
